### ISSUE TITLE
My ways of making Warzone better

### ISSUE THREAD

**Issue by Echological** [WarzoneMC/Warzone#110]
I already dislike the path of where Warzone is going, such as the Clan system, advanced XP system, and even just one kit per map, plus some more.

- Don't add the Clan system: As of now, we're already having issues with the clans (even before the system itself is being implemented). There are some who take it too seriously that it actually ruins the fun of the segment of Warzone. To solve this (if I were the one to decide), I wouldn't add the clan system.

- No advanced XP: We're already being notified that we're gonna have a better XP system; why not just keep it simple? Kills and objectives, that's all I would like for the XP system.

- Have the kits from the OG Warzones: Remember Big Spender, Ninja, Tank, and a bunch of others? Those were fun times, it created diversity and showed people how they really work with each kit; one may be a better rusher, which may title them the Ninja kit and one may be the best defender, it may title them the Tank or the Fire Archer. Having these kits back will create the best diverse community based on the playstyles! And no, don't add Phoenix unless it'll be nerfed a ton (to fit the gameplay with other kits)

- Return the old staff system: Even though that way, the staff may be inactive, but these guys definitely knew what to do and how to manage Warzone-related situations. It was merely the best system!

I know that some people will disagree with my top 3 ideas, but that's because I've been here during 2 Warzones (and 1 Bedwars) and I want to revive the epic quality of Warzone by bringing back these ideas to gain the far more diverse community. If you do disagree, please respond reasonably and provide suggestions without making an argument. Thank you!

**Comment by Arkrus** [comment]
Elaborate on the clan issues. In my experience, I haven't seen any issues.

**Comment by Echological** [comment]
There were occurences where the clan leaders would take it very seriously, for example, Bearinx takes the applicatants harshly and accuse of "insiding" (I'm sure you know what I mean). I want to remove all troubles regarding clans, and make it only available for tournaments/events, and keep it clan-free on regular basis.

**Comment by DeternoMC** [comment]
Like I mean, keep the tournaments system, I'd rather not have clans either; all the good people will just stack on one clan, and I mean, what is clans going to do anyways? Let people have donor perks?

**Comment by BennyDoesTheStuff** [comment]
Even though this issue is a few days old ima put my 2 cents into it and some of the things I think about it:
1 - Yes, Bearinx did try to "inside" the clans but that's because he was just joking around with it. Now that we've had a tournament now and that teams only have 5 - 6 people in them, "insiding" isn't really gonna happen. Same with all good people stacking on 1 team since there's definitely more than 5 good people on Warzone.

2 - What do you consider "advanced XP" to be? Right now, you get XP from kills, wins, loses, and for the objective, which I'm pretty sure is good enough and not too advanced.

3 - If you would look in the TO-DO area in the Github [https://github.com/WarzoneMC/Warzone/projects/1](here) you would see that adding kits is planned for the future, so is a few other features and ideas.

4 - Sorry, but that's most likely not going to happen anytime in the future. Currently, the way Warzone is setup, it's considered as a "Minehut player server" and is not partnered to Minehut. So far, it seems this actually has been working quite well as we've gotten quite a bit of staff members and most, if not all of them are actively playing/moderating the server. [https://i.gyazo.com/f8cc6c5d163bb4e59d9103d19881ba09.png](Moderators)

So yea, that's what I think of some of the things you've pointed out in the issue above.
