### ISSUE TITLE
Speed for the first 30 seconds

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#116]
Maybe everyone should get speed for the first 30 seconds of the game so people can make bridges faster, maybe for people who don't know how to speed bridge or to avoid 1 team getting to middle first and then bow spamming the other team so they can't get across.

**Comment by FieryAU** [comment]
People who can speed bridge would get to the middle in 2 seconds, and the game would most likely end under 4 and a half minutes.

As an alternative, maybe make it so you get a temporary speed boost if you get a killstreak?

**Comment by scorpion808** [comment]
Speed bridging is a skill.  I know it's unfair for the ones that don't know how to speed bridge, but they can always practice this skill. Adding this would not only remove this skills, but it will give rushers an advantage because the other team would "build a bridge for them" which most likely causes the game to end faster. Soon kits will be coming and they might have speed effects so I suggest waiting for the kits to arrive.

**Comment by Palmidence** [comment]
This would be a map change, not a TGM change. As well as this, we don't want to give any incentives to complete the game faster. Speed bridging is already a strategy that has developed over time, and taking that away and giving everyone the same opportunity would not be a good call from a competitive standpoint.

It's an interesting proposal, but not something I'd pursue.

**Comment by tjhubz** [comment]
This is something you can change on the map.json if you ever make a map.
