### ISSUE TITLE
Regenerators

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#128]
You should make it so if your wool is broken you can shift right click where the wool was and it will start to regenerate. Maybe it will take like 3-5 minutes to regenerate? I am not sure what the time will be but I think this could be a cool feature. And maybe you can make it so if someone breaks it while it's regenerating the timer resets and it starts to regenerate again.

**Comment by Arkrus** [comment]
This just unnecessarily extends matches

**Comment by Synconix** [comment]
True

**Comment by Virtualizes** [comment]
As Arkrus said, it would be a pretty cool feature but it just extends matches that don't need to be extended.

**Comment by Palmidence** [comment]
This would be an interesting module, but the issue is that:
- Ultimately, it wouldn't work on all maps. It extends matches unnecessarily, and if we were to add it to only some maps, it would be confusing to users, especially new ones.
- "DTW" does not have anything different than standard DTM. Obsidian DTM maps would be stranger for this module since there's no way to break them up, as DTW just uses the same monuments function and regenerating obsidian monuments would be strange.

**Comment by Synconix** [comment]
_**Yea bad idea, shouldn't have posted it. Issue Closed**_
