### ISSUE TITLE
Command To Stop/Freeze Chat

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#148]
Make a command that makes it so only staff can speak in chat and nobody else can, this will be good for tournaments.

**Comment by Virtualizes** [comment]
+1

**Comment by TheRealPear** [comment]
How would this work with permission-based ranks instead of the standard OP?

**Comment by Synconix** [comment]
Yes

**Comment by Palmidence** [comment]
This is definitely a useful suggestion- I like it! It would be a very resourceful moderation tool.

The only question I have is, should there be flags to indicate the time as to how long chat should be stopped for, and should it send a message to the server? For instance, players should get a message broadcasted to the server specifying that message flow is disabled, and that moderators are able to automate it rather than have to manually start and stop it each time (it would be annoying for tournaments particularly if you had to keep typing it each time, even after you communicate with players for each member that should be in a team and to determine maps, and during matches, etc.)

**Comment by DeternoMC** [comment]
Stop chat as in global chat mute?

Also, you should also add delays in chat messages if you're going to do this, and maybe make donators/vips bypass the chat delays.

**Comment by Virtualizes** [comment]
That is actually a really good idea Deterno.

Perhaps one of us could submit an issue on it when we get the time to.

**Comment by Synconix** [comment]
Maybe change /stopchat to something else like /freezechat or smth
