### ISSUE TITLE
Server freezes after map cycling

### ISSUE THREAD

**Issue by AtditC** [WarzoneMC/Warzone#234]
This started since a day or two. Basically, the server freezes for ~4 seconds after a new map is loaded. In this time, we can't fly, and the chat isn't visible. After it's over, we can see all chat messages which people typed while it was lagging.

**Comment by JapaneseSquid** [comment]
This could be unrelated, but a lot of players (including myself)  have been experiencing random FPS drops as well, most of them freezing the entire screen. It could be due to a lack of restarts, but this is the first time that I have seen this happen.

**Comment by AtditC** [comment]
@JapaneseSquid same

**Comment by MatrixTunnel** [comment]
If the chat laggs then it could be one of three things:

-The server lagged so much that it even made async threads lag
-Your client lagged and the chat caught up afterwards
-The proxy you were connected to lagged but I don't know how switching world's would affect that

The server (to my limited knowledge) restarts every one or two days so that shouldn't be an issue. As for the FPS drop, that’s mostly normal when switching worlds and loading in new chunks

**Comment by tjhubz** [comment]
This has been much improved after Luke's changes in my opinion. Is it still an issue?

**Comment by scorpion808** [comment]
It still is.

**Comment by jellz** [comment]
This issue should be closed, the OP/commenters haven't provided any proof of the issue occurring.
