### ISSUE TITLE
a /nick command

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#250]
A command that changes a player or staff member's nick to whatever is set and shows up in chat, tab, on winning, etc. Would be nice when watching hackers and for various other reasons.

**Comment by TheRealPear** [comment]
Is this staff only? If not, could it be for VIP?

**Comment by jellz** [comment]
Seems unnecessary imo, should just add a /vanish for staff

**Comment by Hordesworn** [comment]
Instead of /vanish, can't you just add a command /spec (makes you spectator and takes you out of the game if you're not in combat) (probably only for staff)

But yeah, /nick or /vanish might be nice because some cheaters know the staff team as they're on the Discord and they can spot them somewhere in the game.

**Comment by jellz** [comment]
Spectator mode still allows your name to be seen in the player list.

**Comment by Hordesworn** [comment]
Ah, should've thought of that one. /vanish would be essential to catching rule-breakers.

**Comment by JapaneseSquid** [comment]
This feature is too handy to be available to VIP. Maybe for staff but I don’t think it should be out to the public until a more expensive rank is implemented
