### ISSUE TITLE
[Suggestion] Allow server owners to pick between MySQL, SQLite, and MongoDB for the API

### ISSUE THREAD

**Issue by TheRealPear** [WarzoneMC/Warzone#326]
Since TGM was designed to be open sourced and used by other server owners, I think this would make it easier for several of us on shared hosting to use the API without having to get a MongoDB instance.

If you can't add support for SQLite, just start with MySQL for now. Sure, we can easily setup TGM without API connected, but this will stop levels, ranks, punishments, etc from working.

**Comment by Draem** [comment]
mongodb really doesn't require too much effort to setup

doesn't really seem needed

**Comment by TheRealPear** [comment]
@Draem The problem is that most shared hosting doesn't even use Node.js or allow Mongo

**Comment by TheRealPear** [comment]
@jellz Think of MCProhosting, BisectHosting, etc. Chances are, someone is using that kind of host with TGM and no way of having a Node.js instance and Mongo (which is hard to setup)

I'm aware that it may take time to implement what I asked. That's... why I made this ticket..? I'm using an OVH VPS myself, but I haven't bothered to setup Mongo. I just thought it'd be a good idea to at least add support for MySQL.

**Comment by jellz** [comment]
@TheRealPear 

> Think of MCProhosting, BisectHosting, etc. Chances are, someone is using that kind of host with TGM and no way of having a Node.js instance and Mongo (which is hard to setup)

Good servers would use their own server to host their services. This allows them to have a website, API, game server, etc... (Hypixel is an exception because they have a deal with MCPH)

Second of all, it's unnecessary. The TGM developers chose to use MongoDB (because Luke is familiar with it), and that's what they're using. Same point as before; you don't ask the project maintainer to add support for more databases, because that would just be rewriting the entire thing over and over again.

Third of all, MongoDB is the standard for Node.js. Stratus' API uses MongoDB too. Just yesterday, I was watching a programming stream, the streamer was creating an application using Node.js - can you guess what database he used?

>  I'm using an OVH VPS myself, but I haven't bothered to setup Mongo.

If the API had used MySQL (or some other SQL database) and I had created an issue asking for RethinkDB and MongoDB support to be added, purely because I 'haven't been bothered to setup Mongo,' would you support that?

Why don't you just deal with it and install MongoDB?

Assuming you're using an Ubuntu server, [here's a tutorial on installing Mongo](https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04).

Yours truly,
Daniel

**Comment by BennyDoesTheStuff** [comment]
Going to close this, I personally feel that it would be easier in the long term to only support MongoDB at the moment. Not only that, but with the lack of developers we have, it's overall better if we make adding features and fixing bugs a priority over supporting other databases
