### ISSUE TITLE
[SUGGESTION] Karma

### ISSUE THREAD

**Issue by Noahvarm** [WarzoneMC/Warzone#34]
**Karma**
Maybe you could add like a karma system like Hypixel has...? So like at the end of every game you say GG or Good Game and you get +(ammount) of karma? And if you say BG you can -(ammount) of karma?

**-_Kron_**

**Comment by TheRealPear** [comment]
Why.

**Comment by Draem** [comment]
why not

**Comment by TheRealPear** [comment]
why copy a popular Minecraft server when Minehut isn't going to get any?

**Comment by BennyDoesTheStuff** [comment]
@TheRealPear How else are crazy ideas and minigames ideas made? Look at famous painters, they copy other paintings they like but change things to make it a unique idea. If Luuke would to implement this "karma" idea Hypixel has, he would most likely change something about it to make it Unique. Look at Shotbow for example, they were the **FIRST** server to connect multiple different servers into 1 proxy. Now look at some of the popular servers a few years later with tons of servers connected and being able to switch to them with just 1 command or less. 

Anyways @Kronchical I don't agree with your idea since I've rarely seen anyone say "BG" and I'm not sure how these "Karma points" would be used.

**Comment by tjhubz** [comment]
Not needed
