### ISSUE TITLE
[SUGGESTION] Bloody Hand

### ISSUE THREAD

**Issue by Noahvarm** [WarzoneMC/Warzone#35]
**Bloody Hand**
I have a suggestion, you cover your wool in glass but whenever glass is broken you get bloody hand and start casually losing heath, kinda like a better defense for wool!

**__-Kronchical__**

**Comment by TheRealPear** [comment]
No.

**Comment by Draem** [comment]
explain your reasoning

**Comment by Echological** [comment]
This does sound pretty good, it's a pretty smart mechanism for when nobody's defending.

**Comment by TheRealPear** [comment]
Well, why would you want to receive damage from breaking wools? Sure, it'll make it realistic but we don't want this to be TOO realistic.

**Comment by Echological** [comment]
Maybe it doesn't even have to be glass, maybe fireworks like we had before. Pear, who even is "we"? It doesn't matter if it's too realistic, because it's just a game. 

I agree with this because almost in every game, there's nobody defending and we can't reach back, so it's pretty smart to have the losing-health mechanism. It also makes it a bit more challenging.

**Comment by realjbtytm** [comment]
This change would affect the strategies and tactics of some players. I think this would be a great addition so that players can watch their health and actions in battle more. I also agree with everything @Echological has said. I also like games to be at least somewhat realistic as I like to be immersed into the game.

**Comment by HazryG** [comment]
Well if you want it, someone has to make it and submit a pull request - this is a community run game after all :)

**Comment by realjbtytm** [comment]
Yeah, haha. But aren't 2 contributors in this discussion right now? Hehe, just kidding.

(But seriously though, I apologize if I have offended the mentioned contributors.)

**Comment by HazryG** [comment]
All I did was contribute win messages ¯\_(ツ)_/¯

**Comment by BennyDoesTheStuff** [comment]
I don't like this idea tbh. This would make it too realistic and especially since there's only 2 or 3 maps in all of TeamGG that has glass in it. Though 1 thing I feel should be added is whenever you break a wool you get mining fatigue for 3 seconds or so. That would make it so you can't break all the wool in 10 seconds or less and it'll make the game longer and possibly even more competitive.

**Comment by Echological** [comment]
It doesn't have to be glass though, it could be poisoning from touching the wool or fireworks.

**Comment by realjbtytm** [comment]
*cough* Maybe from team upgrades like in Sky/BedWars for example? Or a premium rank reward? *cough*

**Comment by Echological** [comment]
I don't think it should be premium-rank rewards, I think it should be some sort of a team upgrade. That way, the game isn't just combat and objective, it needs some twist to it.

**Comment by FactoDoesStuff** [comment]
There aren't enough maps as Benny said to accommodate this idea, and honestly, that would just be too overpowered.

**Comment by realjbtytm** [comment]
Maybe the rate would be at .5 hearts every 15 seconds until the player eats a golden apple or just eats until a full hunger bar?

**Comment by Kronchical** [comment]
I mean like the reason I suggested this is whenever I am playing my team never defends, they all go and attack and we lose because nobody is defending, so if we do that it could be a good defense

**Comment by tjhubz** [comment]
Closed.
