### ISSUE TITLE
Spectators Have Kits.

### ISSUE THREAD

**Issue by Jabboll** [WarzoneMC/Warzone#395]
![image](https://user-images.githubusercontent.com/44612425/49054061-d850f800-f1c0-11e8-9062-d561986a1608.png)

![image](https://user-images.githubusercontent.com/44612425/49054071-e0a93300-f1c0-11e8-8715-eec878757f46.png)
There, :)

**Comment by BennyDoesTheStuff** [comment]
Could you explain more detailed on how to reproduce this?

**Comment by BennyDoesTheStuff** [comment]
I personally haven't experienced this before, if it does happen again please reopen the issue with steps on how to reproduce

**Comment by AtditC** [comment]
I think this has to do with the AFK timer. When you are AFK for 5 minutes as spectator and then try to join a team, it puts you back as spectator immediately. You get the kit as spectator because the AFK timer which puts you in spectator mode might be faster than the code which gives you the kit.

Also, damage indicator isn't allowed on Warzone.
