### ISSUE TITLE
Idea, Server IP on SB

### ISSUE THREAD

**Issue by TRose2000** [WarzoneMC/Warzone#430]
Add the server IP on the scoreboard what you can change in the configuration file

**Comment by AtditC** [comment]
No, that's annoying for gameplay

-1

**Comment by BennyDoesTheStuff** [comment]
I think it would be a pretty good idea. Almost all other servers does it because it advertises the server IP, not only to the player in the game but to any viewers on YouTube if a player makes a video in game.

**Comment by Owehttamy** [comment]
I agree with Benny. Not only would it advertise the server but it would also remind the player what the ip is, and it could use the external ip rather than the Minehut one so more people could possibly start using the external ip which has a better connection and generally make the experience better.
Also, a single extra line to the scoreboard isn’t going to block view of anything such as an incoming enemy. If it ever possibly could, there are more reasons to implement this into the server than not to.

**Comment by TRose2000** [comment]
>           I agree with Benny. Not only would it advertise the server but it would also remind the player what the ip is, and it could use the external ip rather than the Minehut one so more people could possibly start using the external ip which has a better connection and generally make the experience better.
> Also, a single extra line to the scoreboard isn’t going to block view of anything such as an incoming enemy. If it ever possibly could, there are more reasons to implement this into the server than not to.

benny exactly just said a reason lol

**Comment by TRose2000** [comment]
I'm gonna close this one as well.
