### ISSUE TITLE
fix spawn entry prevention pre-game

### ISSUE THREAD

**Issue by Hxnr** [WarzoneMC/Warzone#447]
Before the game starts when you pick a team you are unable to enter the enemy team's spawn when you are flying around

**Comment by Draem** [comment]
The issue source is filters are registered before the game starts. One of the filters is for entering the opponent's spawn point, but since the listener for it gets registered before the match start, you can't enter their spawn point once you've chosen a team.

[This method](https://github.com/WarzoneMC/Warzone/blob/aa3a881e8c811cd111fcf62b6d4b68b2792f400d/TGM/src/main/java/network/warzone/tgm/modules/filter/FilterManagerModule.java#L29) should be changed to `MatchModule#enable` to fix the issue. ![mentioned method image](https://i.imgur.com/7qsvJZg.png)

**Comment by BennyDoesTheStuff** [comment]
Fixed in #460
