### ISSUE TITLE
Tridents & TNT Kills

### ISSUE THREAD

**Issue by SirGoldman-git** [WarzoneMC/Warzone#544]
**Problem:**
When you throw a Trident and kill a user it does not count as a kill for the killer. Same thing with TNT if you kill a user with it or knock them off the island.

**Request:**
Add support for both of those items so users can get credit for the kill. Maybe a funny death message like "player forked player from 10 blocks".

**Comment by Owehttamy** [comment]
Players don't have access to tridents because Warzone uses legacy combat. This means that shields, tridents, crossbows, totems of undying, etc. are not used in this server, especially since it supports version 1.8.9.
As with the TNT, I personally don't think it's necessary for people to get kills from TNT because it would not only be hard to judge who killed who since TNT can create chain explosions, but also because there's a lack of maps that even implement TNT.

**Comment by ThatOneTqnk** [comment]
When a trident ceases you from being alive, there is now a death message thanks to #545
