### ISSUE TITLE
Players only Drop "Useful" Items when Killed

### ISSUE THREAD

**Issue by Owehttamy** [WarzoneMC/Warzone#559]
For quality of life reasons it would be enjoyable to prevent base armor, swords, bows, and tools from being dropped when the player is killed so whoever picks up their loot doesn't have their inventory filled with items that they're not going to need.

I say "base" items because possibly we could let the players drop items that they grabbed from chests such as bows with the flame enchantment on it, or a chestplate with protection.

Another item worth considering is golden apples. If the player who died had golden apples in their inventory should they drop?

**Comment by CrazyisCreeps** [comment]
Rather than making it a plugin orientated thing, what if we just used the item remove module in maps? I agree that base items should be removed, but wouldn't stuff like whether or not to drop gapples fall to the discretion of the author if it suits their map best? (As in, it may fit a TDM better than a CTW, or some other way around).
