### ISSUE TITLE
Toggle Team Chat

### ISSUE THREAD

**Issue by Echological** [WarzoneMC/Warzone#76]
I have two ideas that should be implemented into the Warzone minigame. 

**Toggle Team Chat**
I suggest that we add a command that allows us to toggle between the global chat and the team chat. It's rather annoying that we do "/t" before every message and then send it. There are some people that may disagree because apparently one of the common reasons is "accidentally sending a message that's supposed to be in other chat".

**Comment by BennyDoesTheStuff** [comment]
The toggle team chat personally is actually a pretty good idea, which shouldn't be too hard to implement. Though when it comes to appeals Matrix is actually already working on another cool idea for them, which is kinda similar to what you said, but without the command part since, if you're banned from TeamGG, you kinda can't join the server to do a command.

**Comment by Echological** [comment]
That is true, Benny, but at least the bot should add their username for the one-hour time so that they get the notification. Maybe, it can be a feature in the lobby instead of in the actual server.

**Comment by tjhubz** [comment]
Make separate issues for different suggestions, removed appeals suggestion because we are changing our appeals system.
